eshop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('web.urls')),
    path('admin/', admin.site.urls),
] +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    path('', views.index, name='index'),
    path('productosPorCategoria/<int:categoria_id>',views.productosPorCategoria,name='productosPorCategoria'),
    path('productosPorNombre',views.productosPorNombre,name='productosPorNombre'),
    path('producto/<int:producto_id>',views.productoDetalle,name='producto'),
    path('carrito',views.carrito,name='carrito'),
    path('agregarCarrito/<int:producto_id>',views.agregarCarrito,name='agregarCarrito'),
    path('limpiarCarrito',views.limpiarCarrito,name='limpiarCarrito'),
    path('registrarPedido',views.registrarPedido,name='registrarPedido'),
    path('eliminarProductoCarrito/<int:producto_id>',views.eliminarProductoCarrito,name='eliminarProductoCarrito'),
    path('crearUsuario',views.crearUsuario,name='crearUsuario'),
    path('loginUsuario',views.loginUsuario,name='loginUsuario'),
    path('cuenta',views.cuentaUsuario,name='cuentaUsuario')
] 

web/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.nombre

# class Proveedor(models.Model):
#    rfc = models.CharField(max_length=13,default='')
#    nombre = models.CharField(max_length=50)
#    contacto_compras = models.CharField(max_length=50)
#    email_compras = models.EmailField(max_length=40)
#    cel_compras = models.CharField(max_length=12)
#    contacto_pagos = models.CharField(max_length=50)
#    email_pagos = models.EmailField(max_length=40)
#    cel_pagos = models.CharField(max_length=12)
#    contacto_almacen = models.CharField(max_length=50)
#    email_almacen = models.EmailField(max_length=40)
#    cel_almacen = models.CharField(max_length=12)
#    contacto_otro = models.CharField(max_length=50)
#    email_otro = models.EmailField(max_length=40)
#    cel_otro = models.CharField(max_length=12)
#    telefono = models.CharField(max_length=12)
#    calle = models.CharField(max_length=50)
#    colonia = models.CharField(max_length=50)
#    ciudad = models.CharField(max_length=50)
#    estado = models.CharField(max_length=3)
#    pais = models.CharField(max_length=20)
#    plazo_credito = models.SmallIntegerField(default=0)
#    comentarios = models.TextField(null=True)
#
#    def __str__(self):
#        return self.nombre

class Producto(models.Model):
#    codigo = models.CharField(max_length=20, primary_key=True)
    categoria = models.ForeignKey(Categoria,on_delete=models.RESTRICT)
    nombre = models.CharField(max_length=200)
    descripcion = models.TextField(null=True)
    precio = models.DecimalField(max_digits=9,decimal_places=2)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    imagen = models.ImageField(upload_to='productos',blank=True)
#    sku = models.CharField(max_length=12, default='')
#    marca = models.CharField(max_length=30)
#    proveedor = models.ForeignKey(Proveedor,on_delete=models.RESTRICT)

    def __str__(self):
        return self.nombre


from django.contrib.auth.models import User

class Cliente(models.Model):
    usuario = models.OneToOneField(User,on_delete=models.RESTRICT)
    rfc = models.CharField(max_length=13)
    sexo = models.CharField(max_length=1,default="M")
    telefono = models.CharField(max_length=12)
    fecha_nacimiento = models.DateField(null=True)
    direccion = models.TextField()
    campo_libre = models.CharField(max_length=50)

    def __str__(self):
        return self.rfc

class Pedido(models.Model):
    
    ESTADO_CHOICES = (
        ('0','Solicitado'),
        ('1','Pagado')
    )

    cliente = models.ForeignKey(Cliente,on_delete=models.RESTRICT)   # ForeingKey - relacion de muchos a uno
    fecha_registro = models.DateTimeField(auto_now_add=True)
    numero_pedido = models.CharField(max_length=20,null=True)
    monto_total = models.DecimalField(max_digits=10,decimal_places=2,default=0)
    estado = models.CharField(max_length=1,default='0',choices=ESTADO_CHOICES)   # CON Esto, solo permite 0 o 1

    def __str__(self):
        return self.numero_pedido

class PedidoDetalle(models.Model):
    pedido = models.ForeignKey(Pedido,on_delete=models.RESTRICT)
    producto = models.ForeignKey(Producto,on_delete=models.RESTRICT)
    cantidad = models.IntegerField(default=1)
    subtotal = models.DecimalField(max_digits=10,decimal_places=2)

    def __str__(delf):
        return self.producto.nombre

web/forms.py
from django import forms

class DateInput(forms.DateInput):
    input_type='date'

class ClienteForm(forms.Form):
    SEXO_CHOICES = (
        ('M','Masculino'),
        ('F','Femenino')
    )

    rfc = forms.CharField(label='RFC',max_length=13)
    nombre = forms.CharField(label-'Nombres',max_length=200,required=True)
    apellidos = forms.CharField(label='Apellidos',max_length=200)
    email = forms.EmailField(label='Email',required=True)
    direccion = forms.CharField(label='Direccion',widget=forms.Textarea)
    telefono = forms.CharField(label='Telefono',max_length=20)
    sexo = forms.ChoiceField(label='Sexo',choices=SEXO_CHOICES)
    fecha_nacimiento = forms.DateField(label='Fecha Nacimiento',input_formats=['%Y-%m-%d'],widget=DateInput())

web/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .models import Categoria, Producto

# Create your views here.
""" VISTAS PARA EL CATALOGO DE PRODUCTOS """
def index(request):
    listaProductos = Producto.objects.all()
    listaCategorias = Categoria.objects.all()

    context = {
        'productos' : listaProductos,
        'categorias' : listaCategorias
    }
    return render(request,'index.html', context)

def productosPorCategoria(request,categoria_id):
    """ vista para filtrar productos por categoria """
    objCategoria = Categoria.objects.get(pk=categoria_id)
    listaProductos = objCategoria.producto_set.all()

    listaCategorias = Categoria.objects.all()

    context = {
        'categorias':listaCategorias,
        'productos':listaProductos
    }

    return render(request,'index.html',context)

def productosPorNombre(request):
    """ busqueda de productos por nombre """
    nombre = request.POST['nombre']

    listaProductos = Producto.objects.filter(nombre__contains=nombre)
    listaCategorias = Categoria.objects.all()

    context = {
        'productos':listaProductos,
        'categorias':listaCategorias
    }
    return render(request,'index.html',context)

def productoDetalle(request,producto_id):
    """ vista para el detalle del producto """

    # objProducto = Producto.objects.get(pk=producto_id)
    objProducto = get_object_or_404(Producto,pk=producto_id)
    
    context = {
        'producto': objProducto
    }

    return render(request,'producto.html',context)

""" VISTAS PARA EL CARRITO DE COMPRAS """

from .carrito import Cart

def carrito(request):
    return render(request,'carrito.html')

def agregarCarrito(request,producto_id):
    if request.method == 'POST':
        cantidad = int(request.POST['cantidad'])
    else:
        cantidad = 1
    
    objProducto = Producto.objects.get(pk=producto_id)
    carritoProducto = Cart(request)
    carritoProducto.add(objProducto,cantidad)

    #print(request.session.get("cart"))

    return render(request,'carrito.html')

def limpiarCarrito(request):
    carritoProducto = Cart(request)
    carritoProducto.clear()

    return render(request,'carrito.html')

def eliminarProductoCarrito(request,producto_id):
    objProducto = Producto.objects.get(pk=producto_id)
    carritoProducto = Cart(request)
    carritoProducto.delete(objProducto)

    return render(request,'carrito.html')

def registrarPedido(request):
    pass

""" VISTAS PARA CLIENTES Y USUARIOS """

from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate

def crearUsuario(request):

    if request.method == 'POST':
        dataUsuario = request.POST['nuevoUsuario']
        dataPassword = request.POST['nuevoPassword']

        nuevoUsuario = User.objects.create_user(username=dataUsuario,password=dataPassword)
        if nuevoUsuario is not None:  # si no es vacio, si tiene un valor
            login(request,nuevoUsuario)
            return redirect('/cuenta')

# <!-- {% load crispy_forms_tags %}  -->   linea 2 de cuenta.html

    return render(request,'login.html')

def cuentaUsuario(request):
    return render(request,'cuenta.html')

def loginUsuario(request):
    return render(request,'login.html')

web/templates/carrito.html
{% extends 'layout.html' %}
{% block content %}
    <h1 class="maincont-ttl">Carrito</h1>
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li>Carrito</li>
    </ul>
    <div class="page-styling">
    <div class="woocommerce prod-litems section-list">
        {% for key,value in request.session.cart.items %}
        <article class="prod-li sectls">
            <div class="prod-li-inner">
                <a href="producto.html" class="prod-li-img">
                    <img src="{{ value.imagen }}" alt="">
                </a>
                <div class="prod-li-cont">
                    <div class="prod-li-ttl-wrap">
                        <p>
                            <a href="#">{{value.categoria}}</a>
                        </p>
                        <h3><a href="producto.html">{{ value.nombre }}</a></h3>
                    </div><!--
    No Space
    --><div class="prod-li-prices">
                    <div class="prod-li-price-wrap">
                        <p>Precio</p>
                        <p class="prod-li-price">${{ value.precio }}</p>
                    </div>
                    <div class="prod-li-qnt-wrap">
                        <p class="qnt-wrap prod-li-qnt">
                            <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                            <input type="text" value="{{value.cantidad}}">
                            <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                        </p>
                    </div>
                    <div class="prod-li-total-wrap">
                        <p>Total</p>
                        <p class="prod-li-total">${{value.subtotal}}</p>
                    </div>
                </div><!--
No Space
--></div>
                <div class="prod-li-info">
                    <div class="prod-li-rating-wrap">
                        <p data-rating="5" class="prod-li-rating">
                            <i class="rating-ico" title="1"></i><i class="rating-ico" title="2"></i><i class="rating-ico" title="3"></i><i class="rating-ico" title="4"></i><i class="rating-ico" title="5"></i>
                        </p>
                        <p class="prod-li-rating-count">12</p>
                    </div>
                    <p class="prod-li-add">
                        <a href="{% url 'web:eliminarProductoCarrito' value.producto_id %}" class="button hover-label prod-addbtn"><i class="icon ion-close-round"></i><span>Eliminar</span></a>
                    </p>
                    <p class="prod-li-information">
                        <a href="#" class="hover-label"><i class="icon ion-more"></i><span>Show Information</span></a>
                    </p>
                </div>
            </div>
            <div class="page-styling prod-li-informations">

                <dl class="prod-li-props">
                    <dt>Marca:</dt>
                    <dd><a href="#">{{value.marca}}</a></dd>
                    <dt>Peso:</dt>
                    <dd>{{value.peso}} kg</dd>
                    <dt>Dimensiones:</dt>
                    <dd>{{value.dimension}}</dd>
                    <dt>Сolor:</dt>
                    <dd>{{value.color}}</dd>
                </dl>
            </div>
        </article>
        {% endfor %}
    </div>


    <div class="cart-actions">
        <div class="coupon">
            <input type="text" placeholder="Coupon code">
            <input type="submit" class="button" value="Apply">
        </div>
        <div class="cart-collaterals">
            <a href="{% url 'web:limpiarCarrito' %}" class="checkout-button button">Limpiar Carrito</a> <!-- {% url 'web:limpiarCarrito' %} -->
            <a href="#" class="checkout-button button">Realizar Pedido</a> <!-- {% url 'web:registrarPedido' %} -->
            <div class="order-total">
                <p class="cart-totals-ttl">Total</p>
                <p class="cart-totals-val">${{request.session.cartMontoTotal}}</p>
            </div>
        </div>
    </div>


</div>

{% endblock %}

web/templates/cuenta.html
{% extends 'layout.html' %}
{% block content %}
<h1 class="maincont-ttl">Bienvenido - {{ user.username }}</h1>
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li>Mi Cuenta</li>
    </ul>
    <h2>{{mensaje}}</h2>
    <article class="page-cont">
        <div class="page-styling">
            <div class="auth-wrap">
                <div class="auth-col">
                    <h2>Datos Personales</h2>
                    <form method="post" action="{% url 'web:actualizarCliente' %}" class="register">
                        {% csrf_token %}
                        <!-- {{ frmCliente|crispy }}  ->
                        <p class="auth-submit">
                            <input type="submit" value="Actualizar Datos">
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </article>
{% endblock %}

web/templates/gracias.html
{% extends 'layout.html' %}
{% block content %}
<h1 class="maincont-ttl">Checkout OK</h1>
    <ul class="b-crumbs">
        <li><a href="index.html">Home</a></li>
        <li>COMPRA</li>
    </ul>
    <h2>GRACIAS POR TU COMPRA</h2>    
{% endblock %}

web/templates/includes/catalogo/catalogo.html
<div class="row prod-items prod-items-2">
    {% for producto in productos %}
    <article class="cf-sm-6 cf-md-6 cf-lg-6 col-xs-6 col-sm-6 col-md-6 col-lg-6 sectgl-item">
        <div class="sectgl prod-i">
            <div class="prod-i-top">
                <a class="prod-i-img" href="{% url 'web:producto' producto.id %}">
                    {% if producto.imagen %} 
                        <img src="{{producto.imagen.url}}" alt="">
                    {% else %}
                        <img src="https://via.placeholder.com/250" alt="">
                    {% endif %}
                </a>
                <div class="prod-i-actions">
                    <div class="prod-i-actions-in">
                        <p class="prod-i-cart">
                            <a href="#" class="hover-label prod-addbtn"><i class="icon ion-android-cart"></i><span>Añadir al carrito</span></a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="prod-i-bot">
                <div class="prod-i-info">
                    <p class="prod-i-price">${{producto.precio}}</p>
                    <p class="prod-i-categ"><a href="#">{{producto.categoria}}</a></p>
                </div>
                <h3 class="prod-i-ttl"><a href="{% url 'web:producto' producto.id %}">{{producto.nombre}}</a></h3>
            </div>
        </div>
    </article>
    {% endfor %}
</div>

web/templates/includes/catalogo/categorias.html
<div class="blog-sb-widget multishopcategories_widget">
    <h3 class="widgettitle">Categorias</h3>
    <div class="section-sb-current">
        <ul class="section-sb-list">
            {% for categoria in categorias %}
            <li>
                <a href="{% url 'web:productosPorCategoria' categoria.id %}">
                    <span class="section-sb-label">{{categoria.nombre}} 
                        <span class="count">{{categoria.producto_set.all.count}} </span>
                    </span>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

web/templates/includes/footer.html
{% load static %}
<!--footer-->
    <div class="container-fluid blog-sb-widgets page-styling site-footer">
        <div class="row">
            <div class="col-sm-12 col-md-4 widget align-center-tablet f-logo-wrap">
                <a href="index.html" class="f-logo">
                    <img src="{% static 'img/logo.png' %}" alt="">
                </a>
                <p>Proyecto Ecommerce</p>
                <button class="btn callback">Contacto</button>
            </div>
        </div>
    </div>

web/templates/includes/header.html
{% load static %}
    <!--header-->
    <div class="site-header">

        <p class="h-logo">
            <a href="/"><img src="{% static 'logo1.JPG' %}" alt="Market-Online"></a>
        </p><!--
    No Space
    --><div class="h-shop">

        <form method="post" action="{% url 'web:productosPorNombre' %}" class="h-search" id="h-search">
            {% csrf_token %}
            <input type="text" name="nombre" placeholder="Buscar...">
            <button type="submit"><i class="ion-search"></i></button>
        </form>

        <ul class="h-shop-links">
            <li class="h-search-btn" id="h-search-btn"><i class="ion-search"></i></li>
            
            <li class="h-shop-icon h-profile">
                <a href="auth.html" title="My Account">
                    <i class="ion-android-person"></i>
                </a>
                <ul class="h-profile-links">
                    <li><a href="/login">Login / Registro</a></li>
                    <li><a href="/logout">Logout</a></li>
                </ul>
            </li>

            {% include 'includes/header_carrito.html' %}


        </ul>
    </div></div>

web/templates/includes/header_carrito.html
<li class="h-cart">
    <a class="cart-contents" href="#"> <!-- cart.html -->
        <p class="h-cart-icon">
            <i class="ion-android-cart"></i>
            <span>1</span>
        </p>
        <p class="h-cart-total">${{value.subtotal}}</p>
    </a>
    <div class="widget_shopping_cart">
        <div class="widget_shopping_cart_content">
            <ul class="cart_list">
                
                <li>
                    <a href="#" class="remove">&times;</a>
                    <a href="#">
                        <img src="https://via.placeholder.com/250" alt="">
                        Producto
                    </a>
                    <span class="quantity">1 &times; $100</span>
                </li>
                
            </ul>
            <p class="total"><b>Subtotal:</b> ${{value.subtotal}}</p>
            <p class="buttons">
                <a href="{% url 'web:carrito' %}" class="button">Ver Carrito</a>
                <a href="#" class="button">Pedido</a>
            </p>
        </div>
    </div>
</li>

web/templates/includes/navbar.html
<!--navbar-->
<div class="container-fluid page-styling site-header-before">
    <div class="row">
        <div class="col-lg-4">
            <ul class="links_list links_list-align-left align-center-desktop topbar-social">
                <li>
                    <p class="links_list-value">
                        <a href="http://facebook.com" target="_blank" rel="nofollow">
                            <i class="fa fa-facebook"></i>
                        </a>
                    </p>
                </li>
            </ul>
        </div>
        <div class="col-lg-8">
            <ul class="links_list links_list-align-right align-center-desktop topbar-contacts">
                <li>
                    <p class="links_list-label">
                        Dirección
                    </p>
                    <p class="links_list-value">
                        <a href="http://maps.google.com" target="_blank" rel="nofollow">Calle 123,Lima Perú</a>
                    </p>
                </li>
                <li>
                    <p class="links_list-label">
                        Contacto
                    </p>
                    <p class="links_list-value">
                        <a href="mailto:support@email.com">Support@Email.com</a>
                    </p>
                </li>
                <li>
                    <p class="links_list-label">
                        Telefono
                    </p>
                    <p class="links_list-value">
                        <a href="tel:656-575-2057">+52(656)-575-2057</a>
                    </p>
                </li>
            </ul>
        </div>
    </div>
</div>

web/templates/login.html
{% extends 'layout.html' %}
{% block content %}
    <h1 class="maincont-ttl">Registration / Login</h1>
    <ul class="b-crumbs">
        <li><a href="index.html">Home</a></li>
        <li>Registration & Login</li>
    </ul>                                                <article class="page-cont">
    <div class="page-styling">


        <div class="auth-wrap">
            <div class="auth-col">
                <h2>Login</h2>
                <form method="post" class="login" action="{% url 'web:loginUsuario' %}">
                    {% csrf_token %}
                    <p>
                        <label for="username">E-mail <span class="required">*</span></label>
                        <input type="text" id="username" name="usuario">
                    </p>
                    <p>
                        <label for="password">Password <span class="required">*</span></label>
                        <input type="password" id="password" name="password">
                    </p>
                    <p class="auth-submit">
                        <input type="submit" value="Login">
                        <input type="checkbox" id="rememberme" value="forever">
                        <label for="rememberme">Remember me</label>
                    </p>
                    <p>
                        <label for="alert-danger"> {{error}}</label>
                    </p>
                    <p class="auth-lost_password">
                        <a href="#">Lost your password?</a>
                    </p>
                </form>
            </div>
            <div class="auth-col">
                <h2>Registro</h2>
                <form method="post" class="register" action="{% url 'web:crearUsuario' %}">
                    {% csrf_token %}
                    <p>
                        <label for="reg_email">Email <span class="required">*</span></label>
                        <input type="email" id="reg_email" name="nuevoUsuario">
                    </p>
                    <p>
                        <label for="reg_password">Password <span class="required">*</span></label>
                        <input type="password" id="reg_password" name="nuevoPassword">
                    </p>
                    <p class="auth-submit">
                        <input type="submit" value="Crear Cuenta">
                    </p>
                </form>
            </div>
        </div>


    </div>
</article>

{% endblock %}

web/templates/pedido.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1 class="maincont-ttl">PEDIDO NRO : {{pedido.nro_pedido}}</h1>
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li>Pedido</li>
    </ul>
<div class="page-styling">
    <div class="woocommerce prod-litems section-list">
            <h2>Fecha : {{pedido.fecha_registro}}</h2>
            {% for detalle in pedido.pedidodetalle_set.all %}
            <article class="prod-li sectls">
                <div class="prod-li-inner">
                    <a href="#" class="prod-li-img">
                        <img src="{{ detalle.producto.imagen.url }}" alt="">
                    </a>
                    <div class="prod-li-cont">
                        <div class="prod-li-ttl-wrap">
                            <p>
                                <a href="#">{{detalle.producto.categoria}}</a>
                            </p>
                            <h3><a href="product.html">{{ detalle.producto.nombre }}</a></h3>
                        </div>
                        <div class="prod-li-prices">
                            <div class="prod-li-price-wrap">
                                <p>Precio</p>
                                <p class="prod-li-price">${{detalle.producto.precio}}</p>
                            </div>
                        </div>
                        <div class="prod-li-qnt-wrap">
                            <p class="qnt-wrap prod-li-qnt">
                                <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                                <input type="text" value="{{detalle.cantidad}}">
                                <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                            </p>
                        </div>
                        <div class="prod-li-total-wrap">
                            <p>Total</p>
                            <p class="prod-li-total">${{detalle.subtotal}}</p>
                        </div>
                    </div>
                </div>
            </article>
            {% endfor %}
    </div>
    <div class="cart-actions">
            <div class="cart-collaterals">
                {{ formpaypal.render }}
                <div class="order-total">
                    <p class="cart-totals-ttl">Total</p>
                    <p class="cart-totals-val">${{pedido.monto_total}}</p>
                </div>
            </div>
    </div>
</div>
{% endblock %}

web/templates/plantilla.html
{% extends 'layout.html' %}
{% block content %}
{% endblock %}

web/templates/producto.html
{% extends 'layout.html' %}
{% block content %}
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li><a href="/">Catalog</a></li>
        <li>Producto</li>
    </ul>
    <article>
    <div class="prod">
        <div class="prod-slider-wrap prod-slider-shown">
            <div class="flexslider prod-slider" id="prod-slider">
                <ul class="slides">
                    <li>
                        <a data-fancybox-group="prod" class="fancy-img" href="#">
                            {% if producto.imagen %}
                                <img src="{{producto.imagen.url}}" alt="">
                            {% else %}
                                <img src="https://via.placeholder.com/250" alt="">
                            {% endif %}
                        </a>
                    </li>
                    <li>
                        <a data-fancybox-group="prod" class="fancy-img" href="#">
                            {% if producto.imagen %}
                                <img src="{{producto.imagen.url}}" alt="">
                            {% else %}
                                <img src="https://via.placeholder.com/250" alt="">
                            {% endif %}
                        </a>
                    </li>
                </ul>
                <div class="prod-slider-count"><p>
                    <span class="count-cur">1</span> / <span class="count-all">2</span></p><p class="hover-label prod-slider-zoom">
                    <i class="icon ion-search"></i><span>Zoom In</span></p></div>
            </div>
            <div class="flexslider prod-thumbs" id="prod-thumbs">
                <ul class="slides">
                    <li>
                        {% if producto.imagen %}
                            <img src="{{producto.imagen.url}}" alt="">
                        {% else %}
                            <img src="https://via.placeholder.com/250" alt="">
                        {% endif %}
                    </li>
                    <li>
                        {% if producto.imagen %}
                            <img src="{{producto.imagen.url}}" alt="">
                        {% else %}
                            <img src="https://via.placeholder.com/250" alt="">
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>

        <div class="prod-cont">
            <div class="prod-rating-wrap">
                <p data-rating="4" class="prod-rating">
                    <i class="rating-ico" title="1"></i>
                    <i class="rating-ico" title="2"></i>
                    <i class="rating-ico" title="3"></i>
                    <i class="rating-ico" title="4"></i>
                    <i class="rating-ico" title="5"></i>
                </p>
                <p class="prod-rating-count">7</p>
            </div>
            <p class="prod-categs"><a href="#">{{producto.categoria}}</a></p>
            <h1>{{producto.nombre}}</h1>
            <div class="variations_form cart">
                <p class="prod-price">${{producto.precio}}</p>
                <p class="prod-excerpt">{{producto.descripcion}}
                    <a id="prod-showdesc" class="prod-excerpt-more" href="#">read more</a></p>
                <div class="prod-add">
                    <form action="{% url 'web:agregarCarrito' producto.id %}" method="post">
                        {% csrf_token %}
                        <div class="variations">
                            <div class="variations-row">
                                <div class="label"><label >Сolor</label></div>
                                <div class="value">
                                    <select>
                                        <option value="">Choose an option</option>
                                        <option value="blue">Blue</option>
                                        <option value="green">Green</option>
                                        <option value="yellow">Yellow</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="button"><i class="icon ion-android-cart"></i> Agregar al Carrito</button>
                        <p class="qnt-wrap prod-li-qnt">
                            <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                            <input type="text" name="cantidad" value="1">
                            <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                        </p>
                    </form>
                </div>
            </div>
            <div class="prod-props">
                <dl class="product_meta">
                    
                    
                </dl>
            </div>
        </div>
    </div>


    

</article>

{% endblock %}